# Generated by Django 5.1.1 on 2024-09-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fazenda', '0005_rename_plantio_cultivo_rename_plantio_dados_cultivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
    ]
